# Generated by Django 4.1.13 on 2024-04-26 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_surveyresponse_alter_usermodel_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalSurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question1', models.CharField(choices=[('very_satisfied', 'Very Satisfied'), ('satisfied', 'Satisfied'), ('neutral', 'Neutral'), ('dissatisfied', 'Dissatisfied'), ('very_dissatisfied', 'Very Dissatisfied')], max_length=20)),
                ('question2', models.TextField()),
                ('question3', models.CharField(choices=[('very_effective', 'Very Effective'), ('effective', 'Effective'), ('neutral', 'Neutral'), ('ineffective', 'Ineffective'), ('very_ineffective', 'Very Ineffective')], max_length=20)),
                ('question4', models.CharField(max_length=100)),
                ('question5', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('unsure', 'Unsure')], max_length=10)),
                ('question6', models.CharField(max_length=100)),
                ('question7', models.TextField()),
                ('question8', models.CharField(choices=[('very_satisfied', 'Very Satisfied'), ('satisfied', 'Satisfied'), ('neutral', 'Neutral'), ('dissatisfied', 'Dissatisfied'), ('very_dissatisfied', 'Very Dissatisfied')], max_length=20)),
            ],
        ),
    ]
