# Generated by Django 4.1.13 on 2024-04-26 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_educationalsurveyresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('survey_type', models.CharField(choices=[('product_feedback', 'Research Survey'), ('customer_service', 'Educational Survey'), ('website_experience', 'Gaming Survey'), ('filmy_survey', 'Filmy Survey')], max_length=20)),
                ('customer_feedback', models.TextField()),
            ],
        ),
    ]
