# Generated by Django 4.1.13 on 2024-04-27 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_surveyresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmySurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_genre', models.CharField(max_length=100)),
                ('movies_watched_per_month', models.PositiveIntegerField()),
                ('movie_genres_enjoyed', models.CharField(max_length=100)),
                ('movie_watching_experience_rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)])),
                ('movie_platform_most_used', models.CharField(max_length=100)),
            ],
        ),
    ]
